remote_theme: jekyll/minima
ignore_theme_config: true

# minima:
#   skin: dark

title: Quantum Information Science
description: This website acts as a hub for learning materials in quantum information science.
