name: Deploy book

on:
  push:
    branches:
      - master

jobs:
  bookdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Yarn packages
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev imagemagick libmagick++-dev libpoppler-cpp-dev

      - name: Setup R
        uses: r-lib/actions/setup-r@master

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: r-${{ hashFiles('DESCRIPTION') }}

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v1

      - name: Setup TinyTeX
        uses: r-lib/actions/setup-tinytex@v1

      - name: Install R packages
        run: |
          R -e "install.packages('bookdown')"
          R -e "install.packages('magick')"
          R -e "install.packages('pdftools')"

      - name: Build site
        run: ./build.R

      - name: Deploy to build branch
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: build
          FOLDER: book
