name: Deploy preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  bookdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Yarn packages
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev imagemagick libmagick++-dev libpoppler-cpp-dev

      - name: Setup R
        uses: r-lib/actions/setup-r@master

      - name: Cache R packages
        uses: actions/cache@v2
        id: cache-r-packages
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v1

      - name: Setup TinyTeX
        uses: r-lib/actions/setup-tinytex@v1

      - name: Install R packages
        if: steps.cache-r-packages.outputs.cache-hit != 'true'
        run: |
          R -e "install.packages('bookdown')"
          R -e "install.packages('magick')"
          R -e "install.packages('pdftools')"

      - name: Build site
        run: |
          R -e "bookdown::render_book('index.Rmd','bookdown::gitbook',output_dir = 'book',config_file = '_bookdown.yml')"
      
      - name: Netlify
        uses: South-Paw/action-netlify-deploy@v1.2.0
        id: netlify
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: './book'
          draft: true
          comment-on-pr: true
